// =============================================================================
// Copyright (c) 2026 Lumees Lab / Hasan Kurşun
// SPDX-License-Identifier: Apache-2.0 WITH Commons-Clause
//
// Licensed under the Apache License 2.0 with Commons Clause restriction.
// You may use this file freely for non-commercial purposes (academic,
// research, hobby, education, personal projects).
//
// COMMERCIAL USE requires a separate license from Lumees Lab.
// Contact: info@lumeeslab.com · https://lumeeslab.com
// =============================================================================
// =============================================================================
// CORDIC IP - Single Pipeline Stage
// =============================================================================
// Implements one micro-rotation for all three coordinate systems.
//
// Equations per stage index `STAGE_IDX`:
//
//   d = (mode==ROTATION)  ? sign(z) :
//       (coord==HYPR)     ? sign(y) : -sign(y)
//
//   Circular  (mu= 1): x' = x - d*(y >> shift), y' = y + d*(x >> shift)
//   Linear    (mu= 0): x' = x,                  y' = y + d*(x >> shift)
//   Hyperbolic(mu=-1): x' = x + d*(y >> shift), y' = y + d*(x >> shift)
//
//   z' = z - d * alpha[STAGE_IDX]    (alpha = atan/atanh/2^-shift table)
//
// The `sat` field is propagated OR-cumulatively (never cleared by a stage).
// Saturation is only generated by cordic_pre_proc and cordic_post_proc.
// =============================================================================

`timescale 1ns/1ps

import cordic_pkg::*;

module cordic_stage #(
  parameter int STAGE_IDX = 0     // Stage number (0-based)
) (
  input  logic        clk,
  input  logic        rst_n,
  input  cordic_data_t  din,
  output cordic_data_t  dout
);

  // -------------------------------------------------------------------------
  // Shift amount: circular → STAGE_IDX; hyperbolic → hypr_shift(STAGE_IDX)
  // Linear uses same shift as circular
  // -------------------------------------------------------------------------
  localparam int CIRC_SHIFT     = STAGE_IDX;
  localparam int HYPR_SHIFT_VAL = hypr_shift(STAGE_IDX);

  // Pre-computed angle constants (evaluated at elaboration from FRAC_BITS)
  localparam logic signed [DATA_WIDTH-1:0] ALPHA_CIRC = atan_lut(STAGE_IDX);
  localparam logic signed [DATA_WIDTH-1:0] ALPHA_HYPR = atanh_lut(STAGE_IDX);

  // Linear alpha: 2^-STAGE_IDX in Q2.FRAC_BITS  =  1 << (FRAC_BITS - STAGE_IDX)
  // Use 64-bit shift to support DATA_WIDTH up to 48 without overflow.
  localparam int LINR_ALPHA_SHIFT = (STAGE_IDX <= FRAC_BITS) ? FRAC_BITS - STAGE_IDX : 0;
  localparam logic signed [DATA_WIDTH-1:0] ALPHA_LINR =
      (STAGE_IDX <= FRAC_BITS) ? DATA_WIDTH'(64'h1 << LINR_ALPHA_SHIFT) : '0;

  // -------------------------------------------------------------------------
  // Combinational intermediates (Vivado/DC compatible — no automatic in FF)
  // -------------------------------------------------------------------------
  logic signed [DATA_WIDTH-1:0] stg_x, stg_y, stg_z;
  logic signed [DATA_WIDTH-1:0] stg_xs, stg_ys;
  logic signed [DATA_WIDTH-1:0] stg_alpha;
  logic                          stg_d;
  logic signed [DATA_WIDTH-1:0] next_x, next_y, next_z;

  always_comb begin
    stg_x = din.x;
    stg_y = din.y;
    stg_z = din.z;

    // Direction decision
    unique case (din.mode)
      ROTATION : stg_d = ~stg_z[DATA_WIDTH-1];
      VECTORING: stg_d = (din.coord == HYPR) ? ~stg_y[DATA_WIDTH-1] : stg_y[DATA_WIDTH-1];
      default:   stg_d = ~stg_z[DATA_WIDTH-1];
    endcase

    // Shifted operands
    unique case (din.coord)
      CIRC, LINR: begin stg_xs = stg_x >>> CIRC_SHIFT;     stg_ys = stg_y >>> CIRC_SHIFT;     end
      HYPR:       begin stg_xs = stg_x >>> HYPR_SHIFT_VAL;  stg_ys = stg_y >>> HYPR_SHIFT_VAL;  end
      default:    begin stg_xs = stg_x >>> CIRC_SHIFT;     stg_ys = stg_y >>> CIRC_SHIFT;     end
    endcase

    // Angle constant
    unique case (din.coord)
      CIRC:    stg_alpha = ALPHA_CIRC;
      LINR:    stg_alpha = ALPHA_LINR;
      HYPR:    stg_alpha = ALPHA_HYPR;
      default: stg_alpha = ALPHA_CIRC;
    endcase

    // Next x, y
    unique case (din.coord)
      CIRC:    begin next_x = stg_d ? (stg_x - stg_ys) : (stg_x + stg_ys);
                     next_y = stg_d ? (stg_y + stg_xs) : (stg_y - stg_xs); end
      LINR:    begin next_x = stg_x;
                     next_y = stg_d ? (stg_y + stg_xs) : (stg_y - stg_xs); end
      HYPR:    begin next_x = stg_d ? (stg_x + stg_ys) : (stg_x - stg_ys);
                     next_y = stg_d ? (stg_y + stg_xs) : (stg_y - stg_xs); end
      default: begin next_x = stg_x; next_y = stg_y; end
    endcase

    // Next z
    next_z = stg_d ? (stg_z - stg_alpha) : (stg_z + stg_alpha);
  end

  // -------------------------------------------------------------------------
  // Registered stage output
  // -------------------------------------------------------------------------
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      dout <= '0;
    end else begin
      dout.coord <= din.coord;
      dout.mode  <= din.mode;
      dout.tag   <= din.tag;
      dout.valid <= din.valid;
      dout.sat   <= din.sat;

      if (din.valid) begin
        dout.x <= next_x;
        dout.y <= next_y;
        dout.z <= next_z;
      end else begin
        dout.x <= din.x;
        dout.y <= din.y;
        dout.z <= din.z;
      end
    end
  end

endmodule : cordic_stage
