// =============================================================================
// Copyright (c) 2026 Lumees Lab / Hasan Kurşun
// SPDX-License-Identifier: Apache-2.0 WITH Commons-Clause
//
// Licensed under the Apache License 2.0 with Commons Clause restriction.
// You may use this file freely for non-commercial purposes (academic,
// research, hobby, education, personal projects).
//
// COMMERCIAL USE requires a separate license from Lumees Lab.
// Contact: info@lumeeslab.com · https://lumeeslab.com
// =============================================================================
// =============================================================================
// CORDIC IP - Single Pipeline Stage
// =============================================================================
// Implements one micro-rotation for all three coordinate systems.
//
// Equations per stage index `STAGE_IDX`:
//
//   d = (mode==ROTATION)  ? sign(z) :
//       (coord==HYPR)     ? sign(y) : -sign(y)
//
//   Circular  (mu= 1): x' = x - d*(y >> shift), y' = y + d*(x >> shift)
//   Linear    (mu= 0): x' = x,                  y' = y + d*(x >> shift)
//   Hyperbolic(mu=-1): x' = x + d*(y >> shift), y' = y + d*(x >> shift)
//
//   z' = z - d * alpha[STAGE_IDX]    (alpha = atan/atanh/2^-shift table)
//
// The `sat` field is propagated OR-cumulatively (never cleared by a stage).
// Saturation is only generated by cordic_pre_proc and cordic_post_proc.
// =============================================================================

`timescale 1ns/1ps

import cordic_pkg::*;

module cordic_stage #(
  parameter int STAGE_IDX = 0     // Stage number (0-based)
) (
  input  logic        clk,
  input  logic        rst_n,
  input  cordic_data_t  din,
  output cordic_data_t  dout
);

  // -------------------------------------------------------------------------
  // Shift amount: circular → STAGE_IDX; hyperbolic → hypr_shift(STAGE_IDX)
  // Linear uses same shift as circular
  // -------------------------------------------------------------------------
  localparam int CIRC_SHIFT     = STAGE_IDX;
  localparam int HYPR_SHIFT_VAL = hypr_shift(STAGE_IDX);

  // Pre-computed angle constants (evaluated at elaboration from FRAC_BITS)
  localparam logic signed [DATA_WIDTH-1:0] ALPHA_CIRC = atan_lut(STAGE_IDX);
  localparam logic signed [DATA_WIDTH-1:0] ALPHA_HYPR = atanh_lut(STAGE_IDX);

  // Linear alpha: 2^-STAGE_IDX in Q2.FRAC_BITS  =  1 << (FRAC_BITS - STAGE_IDX)
  // Use 64-bit shift to support DATA_WIDTH up to 48 without overflow.
  localparam int LINR_ALPHA_SHIFT = (STAGE_IDX <= FRAC_BITS) ? FRAC_BITS - STAGE_IDX : 0;
  localparam logic signed [DATA_WIDTH-1:0] ALPHA_LINR =
      (STAGE_IDX <= FRAC_BITS) ? DATA_WIDTH'(64'h1 << LINR_ALPHA_SHIFT) : '0;

  // -------------------------------------------------------------------------
  // Stage logic
  // -------------------------------------------------------------------------
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      dout <= '0;
    end else begin
      // Propagate metadata (including sticky sat)
      dout.coord <= din.coord;
      dout.mode  <= din.mode;
      dout.tag   <= din.tag;
      dout.valid <= din.valid;
      dout.sat   <= din.sat;   // propagate — only pre/post_proc set new sat

      if (din.valid) begin
        automatic logic signed [DATA_WIDTH-1:0] x, y, z;
        automatic logic signed [DATA_WIDTH-1:0] xs, ys;   // shifted values
        automatic logic signed [DATA_WIDTH-1:0] alpha;
        automatic logic                          d;        // rotation direction (+1=1, -1=0)

        x = din.x;
        y = din.y;
        z = din.z;

        // ------------------------------------------------------------------
        // Direction decision
        // ------------------------------------------------------------------
        unique case (din.mode)
          ROTATION : d = ~z[DATA_WIDTH-1];  // 1 if z>=0
          VECTORING: begin
            if (din.coord == HYPR)
              d = ~y[DATA_WIDTH-1];   // 1 if y>=0
            else
              d = y[DATA_WIDTH-1];    // 1 if y<0  (drive y→0 by adding when y<0)
          end
          default: d = ~z[DATA_WIDTH-1];
        endcase

        // ------------------------------------------------------------------
        // Shifted operands (arithmetic right shift — truncating)
        // ------------------------------------------------------------------
        unique case (din.coord)
          CIRC, LINR: begin
            xs = x >>> CIRC_SHIFT;
            ys = y >>> CIRC_SHIFT;
          end
          HYPR: begin
            xs = x >>> HYPR_SHIFT_VAL;
            ys = y >>> HYPR_SHIFT_VAL;
          end
          default: begin
            xs = x >>> CIRC_SHIFT;
            ys = y >>> CIRC_SHIFT;
          end
        endcase

        // ------------------------------------------------------------------
        // Angle constant selection
        // ------------------------------------------------------------------
        unique case (din.coord)
          CIRC:    alpha = ALPHA_CIRC;
          LINR:    alpha = ALPHA_LINR;
          HYPR:    alpha = ALPHA_HYPR;
          default: alpha = ALPHA_CIRC;
        endcase

        // ------------------------------------------------------------------
        // Update x, y, z
        // ------------------------------------------------------------------
        unique case (din.coord)
          CIRC: begin
            dout.x <= d ? (x - ys) : (x + ys);
            dout.y <= d ? (y + xs) : (y - xs);
          end
          LINR: begin
            dout.x <= x;
            dout.y <= d ? (y + xs) : (y - xs);
          end
          HYPR: begin
            dout.x <= d ? (x + ys) : (x - ys);
            dout.y <= d ? (y + xs) : (y - xs);
          end
          default: begin
            dout.x <= x;
            dout.y <= y;
          end
        endcase

        // z' = z ∓ alpha
        dout.z <= d ? (z - alpha) : (z + alpha);

      end else begin
        dout.x <= din.x;
        dout.y <= din.y;
        dout.z <= din.z;
      end
    end
  end

endmodule : cordic_stage
